// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs5zHX2wpZkVBkmbT397Y-rLiLNykiWsU',
    appId: '1:145877970005:web:27f58d1b2b8a7d683a78dc',
    messagingSenderId: '145877970005',
    projectId: 'latestnew-463b6',
    authDomain: 'latestnew-463b6.firebaseapp.com',
    databaseURL: 'https://latestnew-463b6-default-rtdb.firebaseio.com',
    storageBucket: 'latestnew-463b6.firebasestorage.app',
    measurementId: 'G-CM9HVY87PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWSC0N4B19CWFONJZnvpm7t75GUfpwrtA',
    appId: '1:145877970005:android:1d9d8b49db16b8eb3a78dc',
    messagingSenderId: '145877970005',
    projectId: 'latestnew-463b6',
    databaseURL: 'https://latestnew-463b6-default-rtdb.firebaseio.com',
    storageBucket: 'latestnew-463b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6um0iTzIrO0FoeX5B8-mvh4ifuTaWkQc',
    appId: '1:145877970005:ios:50d936a6b2aadb643a78dc',
    messagingSenderId: '145877970005',
    projectId: 'latestnew-463b6',
    databaseURL: 'https://latestnew-463b6-default-rtdb.firebaseio.com',
    storageBucket: 'latestnew-463b6.firebasestorage.app',
    iosBundleId: 'com.example.skillAuction',
  );
}
